/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SeriesNewRouteImport } from './routes/series/new'
import { Route as SeriesSlugEditRouteImport } from './routes/series/$slug/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesNewRoute = SeriesNewRouteImport.update({
  id: '/series/new',
  path: '/series/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugEditRoute = SeriesSlugEditRouteImport.update({
  id: '/series/$slug/edit',
  path: '/series/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/series/new': typeof SeriesNewRoute
  '/series/$slug/edit': typeof SeriesSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/series/new': typeof SeriesNewRoute
  '/series/$slug/edit': typeof SeriesSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/series/new': typeof SeriesNewRoute
  '/series/$slug/edit': typeof SeriesSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/login' | '/series/new' | '/series/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/login' | '/series/new' | '/series/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/series/new'
    | '/series/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SeriesNewRoute: typeof SeriesNewRoute
  SeriesSlugEditRoute: typeof SeriesSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/new': {
      id: '/series/new'
      path: '/series/new'
      fullPath: '/series/new'
      preLoaderRoute: typeof SeriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug/edit': {
      id: '/series/$slug/edit'
      path: '/series/$slug/edit'
      fullPath: '/series/$slug/edit'
      preLoaderRoute: typeof SeriesSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SeriesNewRoute: SeriesNewRoute,
  SeriesSlugEditRoute: SeriesSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
