/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminApprovalQueueRouteImport } from './routes/admin_.approval-queue'
import { Route as AdminTurnstileRouteImport } from './routes/admin_.turnstile'
import { Route as EntriesIdRouteImport } from './routes/entries/$id'
import { Route as EntriesDeleteRouteImport } from './routes/entries/delete'
import { Route as EntriesNewRouteImport } from './routes/entries/new'
import { Route as SeriesNewRouteImport } from './routes/series/new'
import { Route as SeriesSlugIndexRouteImport } from './routes/series/$slug/index'
import { Route as SeriesSlugEditRouteImport } from './routes/series/$slug/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalQueueRoute = AdminApprovalQueueRouteImport.update({
  id: '/admin_/approval-queue',
  path: '/admin/approval-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTurnstileRoute = AdminTurnstileRouteImport.update({
  id: '/admin_/turnstile',
  path: '/admin/turnstile',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdRoute = EntriesIdRouteImport.update({
  id: '/entries/$id',
  path: '/entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesDeleteRoute = EntriesDeleteRouteImport.update({
  id: '/entries/delete',
  path: '/entries/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesNewRoute = EntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesNewRoute = SeriesNewRouteImport.update({
  id: '/series/new',
  path: '/series/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugIndexRoute = SeriesSlugIndexRouteImport.update({
  id: '/series/$slug/',
  path: '/series/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugEditRoute = SeriesSlugEditRouteImport.update({
  id: '/series/$slug/edit',
  path: '/series/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/downloads': typeof DownloadsRoute
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/approval-queue': typeof AdminApprovalQueueRoute
  '/admin/turnstile': typeof AdminTurnstileRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/delete': typeof EntriesDeleteRoute
  '/entries/new': typeof EntriesNewRoute
  '/series/new': typeof SeriesNewRoute
  '/series/$slug/edit': typeof SeriesSlugEditRoute
  '/series/$slug/': typeof SeriesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/downloads': typeof DownloadsRoute
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/approval-queue': typeof AdminApprovalQueueRoute
  '/admin/turnstile': typeof AdminTurnstileRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/delete': typeof EntriesDeleteRoute
  '/entries/new': typeof EntriesNewRoute
  '/series/new': typeof SeriesNewRoute
  '/series/$slug/edit': typeof SeriesSlugEditRoute
  '/series/$slug': typeof SeriesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/downloads': typeof DownloadsRoute
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin_/approval-queue': typeof AdminApprovalQueueRoute
  '/admin_/turnstile': typeof AdminTurnstileRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/delete': typeof EntriesDeleteRoute
  '/entries/new': typeof EntriesNewRoute
  '/series/new': typeof SeriesNewRoute
  '/series/$slug/edit': typeof SeriesSlugEditRoute
  '/series/$slug/': typeof SeriesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/downloads'
    | '/login'
    | '/preferences'
    | '/reset-password'
    | '/admin/approval-queue'
    | '/admin/turnstile'
    | '/entries/$id'
    | '/entries/delete'
    | '/entries/new'
    | '/series/new'
    | '/series/$slug/edit'
    | '/series/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/downloads'
    | '/login'
    | '/preferences'
    | '/reset-password'
    | '/admin/approval-queue'
    | '/admin/turnstile'
    | '/entries/$id'
    | '/entries/delete'
    | '/entries/new'
    | '/series/new'
    | '/series/$slug/edit'
    | '/series/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/downloads'
    | '/login'
    | '/preferences'
    | '/reset-password'
    | '/admin_/approval-queue'
    | '/admin_/turnstile'
    | '/entries/$id'
    | '/entries/delete'
    | '/entries/new'
    | '/series/new'
    | '/series/$slug/edit'
    | '/series/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DownloadsRoute: typeof DownloadsRoute
  LoginRoute: typeof LoginRoute
  PreferencesRoute: typeof PreferencesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminApprovalQueueRoute: typeof AdminApprovalQueueRoute
  AdminTurnstileRoute: typeof AdminTurnstileRoute
  EntriesIdRoute: typeof EntriesIdRoute
  EntriesDeleteRoute: typeof EntriesDeleteRoute
  EntriesNewRoute: typeof EntriesNewRoute
  SeriesNewRoute: typeof SeriesNewRoute
  SeriesSlugEditRoute: typeof SeriesSlugEditRoute
  SeriesSlugIndexRoute: typeof SeriesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/approval-queue': {
      id: '/admin_/approval-queue'
      path: '/admin/approval-queue'
      fullPath: '/admin/approval-queue'
      preLoaderRoute: typeof AdminApprovalQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/turnstile': {
      id: '/admin_/turnstile'
      path: '/admin/turnstile'
      fullPath: '/admin/turnstile'
      preLoaderRoute: typeof AdminTurnstileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id': {
      id: '/entries/$id'
      path: '/entries/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof EntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/delete': {
      id: '/entries/delete'
      path: '/entries/delete'
      fullPath: '/entries/delete'
      preLoaderRoute: typeof EntriesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/new': {
      id: '/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof EntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/new': {
      id: '/series/new'
      path: '/series/new'
      fullPath: '/series/new'
      preLoaderRoute: typeof SeriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug/': {
      id: '/series/$slug/'
      path: '/series/$slug'
      fullPath: '/series/$slug/'
      preLoaderRoute: typeof SeriesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug/edit': {
      id: '/series/$slug/edit'
      path: '/series/$slug/edit'
      fullPath: '/series/$slug/edit'
      preLoaderRoute: typeof SeriesSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DownloadsRoute: DownloadsRoute,
  LoginRoute: LoginRoute,
  PreferencesRoute: PreferencesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminApprovalQueueRoute: AdminApprovalQueueRoute,
  AdminTurnstileRoute: AdminTurnstileRoute,
  EntriesIdRoute: EntriesIdRoute,
  EntriesDeleteRoute: EntriesDeleteRoute,
  EntriesNewRoute: EntriesNewRoute,
  SeriesNewRoute: SeriesNewRoute,
  SeriesSlugEditRoute: SeriesSlugEditRoute,
  SeriesSlugIndexRoute: SeriesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
